### ISSUE TITLE
First release architectural proposal

### ISSUE THREAD

**Issue by jufantozzi** [courselab/pollex#32]
It's important to have solidified somewhere the overview architecture, with whatever supporting written documentation, as necessary. This way, a clear view and understanding of the application components and their high-level interactions as a whole is made possible (or at least much easier). This should come in the form of a proposal document 

On the "how", >my take< is that google docs are useful and easier (than Github) for reviewing these in its early stages, but once it gets to a better shape, we should introduce it to the repository as well.

**Comment by FulecoRafa** [comment]
Diagram for architecture already created:
https://github.com/courselab/pollex/tree/develop/docs/design
missing written explanation.
